#!/bin/sh
#
# Executed by startx (run your window manager from here)

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$XDG_CONFIG_HOME/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

systemctl --user import-environment DISPLAY XAUTHORITY
if which dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
fi

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ Autostart (remember to background)                                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
xrandr --output DVI-0 --primary --output HDMI-0 --right-of DVI-0 &

# Not using daemon since it doesn't work (possibly AMD gfx is issue)
# https://github.com/chjj/compton/issues/176
# https://www.reddit.com/r/archlinux/comments/4ffsrt/compton_freezing_with_b/
compton &

# Set desktop background colour (xsetroot doesnt work with compton)
hsetroot -solid "#000000" &

urxvtd --quiet --fork --opendisplay  &

udiskie --tray &

unclutter &

# WM needs to be the last entry
exec i3 -V  >>  ~/i3.log 2>&1
