theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "custom"
command = "uptime --pretty | sed -E 's/ week(s)?,/w/g; s/ day(s)?,/d/; s/ hour(s)?,/h/; s/ minute(s)?/m/'"
interval = 600
on_click = "true"

[[block]]
block = "pacman"
interval = 600

[[block]]
block = "music"
player = "mpd"
buttons = ["play", "prev", "next"]
marquee_speed = 0.075
marquee_interval = 3
max_width = 50

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/mnt/hdd1"
alias = "gen"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mum}MB({Mup}%)"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
device = "enp3s0"

[[block]]
block = "custom"
command = "fish --command='echo $SOUND_SOURCE'"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %H:%M:%S"

[[block]]
block = "custom"
command = "fish --command=ime_status"
on_click = "fish --command=ibus-toggle"

[[block]]
block = "custom"
interval = 5
command = "dropbox-cli status"

[[block]]
block = "custom"
command = "fish --command=check_kernel"
