[icons]
# Choices: none, awesome, material
name = "awesome"

[theme]
# Choices: plain, solarized-dark, slick
name = "solarized-dark"
[theme.overrides]
separator = "<span font='DejaVu Mono Sans 12'></span>"
#separator_fg = "#ffffff"
separator_bg = "auto"

[[block]]
block = "pacman"
interval = 600

#TODO
#[[block]]
#block = "custom"
#command = "checkupdates && pikaur --query --sysupgrade --aur 2>/dev/null"

[[block]]
block = "custom"
command = "uptime --pretty | sed --regexp-extended 's/ week(s)?,/w/g; s/ day(s)?,/d/; s/ hour(s)?,/h/; s/ minute(s)?/m/'"
interval = 600
on_click = "true"

[[block]]
block = "music"
player = "mpd"
buttons = ["play", "prev", "next"]
marquee_speed = 0.8
marquee_interval = 3
max_width = 25

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/mnt/general"
alias = "gen"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB({Mupi}%)"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"


[[block]]
block = "custom"
command = "fish --command='check_vpn --barmode'"
interval = 60

[[block]]
block = "net"
device = "enp3s0"

#[[block]]
#block = "custom"
#command = "fish --command='echo $SOUND_SOURCE'"
#interval = 5
#on_click = "fish --command='switchaudio'"

#[[block]]
#block = "custom_dbus"
#name = "SoundDevice"

[[block]]
block = "sound"

#[[block]]
#block = "custom"
#interval = 5
#command = "dropbox-cli status | head --bytes=4"

[[block]]
block = "custom"
command = "fish --command=check_kernel"

[[block]]
block = "custom"
# Show number of X11 apps running
command = "fish --command='check_xclients --barmode'"
interval = 5

#[[block]]
#block = "ibus"

#[[block]]
#block = "custom"
#command = "fish --command=ime_status"
#on_click = "fish --command=ibus-toggle"
#interval = 5

#[[block]]
#block = "weather"
#format = "{temp}° {wind}m/s {direction}"
#service = { name = "openweathermap", api_key = "3bddca882b9b2c3e463785fb9f0df35d", city_id = "1862627", units = "metric" }

[[block]]
block = "custom"
command = "fish --command=phone_battery_status"
interval = 60

[[block]]
block = "custom"
command = "fish --command=tv_status --barmode"
interval = 60

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %H:%M"
