[icons]
# font awesome
Signal = ""
firefox = ""
firefox-nightly = ""
Alacritty = ""
kitty = ""
foot = ""
vim = ""
micro = ""
nano = ""
gedit = ""
code-oss = ""
github = ""
google = ""
private_browsing = ""
Google-chrome = ""
ranger = ""
Kodi = ""
Steam = ""
steam = ""
gamescope = ""
ncmpcpp = ""
imv = ""
Sonixd = ""
youtube-viewer = ""
mpv =  ""
vlc =  ""
"org.jellyfin.jellyfinmediaplayer" =  ""
"org.pwmt.zathura" = ""
"org.https://nomacs.nomacs" = ""
"virt-manager" = ""

[aliases]
ghb = "HandBrake"

[general]
separator = ""
