[icons]
name = "none"

[theme]
name = "slick"
[theme.overrides]
separator = ""
separator_bg = "auto"
idle_bg = "#000000"
alternating_tint_bg = "#444444"

[[block]]
block = "pacman"
interval = 600

#TODO
#[[block]]
#block = "custom"
#command = "checkupdates && pikaur --query --sysupgrade --aur 2>/dev/null"

[[block]]
block = "custom"
command = "uptime --pretty | sed --regexp-extended 's/ week(s)?,/w/g; s/ day(s)?,/d/; s/ hour(s)?,/h/; s/ minute(s)?/m/'"
interval = 600
on_click = "true"

[[block]]
block = "music"
player = "mpd"
marquee_speed = 0.8
marquee_interval = 3
max_width = 25

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/mnt/general"
alias = "gen"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB({Mupi}%)"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "custom"
command = "fish --command='check_vpn --barmode'"
interval = 60

[[block]]
block = "net"
device = "enp3s0"

#[[block]]
#block = "custom_dbus"
#name = "SoundDevice"

# if have issues then disable this block until it has been cleared of unwraps
[[block]]
block = "sound"
driver = "pulseaudio"
on_click = "swaymsg exec 'pavucontrol'"

[[block]]
block = "custom"
command = "fish --command='check_kernel --barmode'"

[[block]]
block = "custom"
# Show number of X11 apps running
command = "fish --command='check_xclients --barmode'"
interval = 5

[[block]]
block = "ibus"
[block.mappings]
"mozc-jp" = "JP"
"xkb:us::eng" = "EN"

[[block]]
block = "custom"
command = "fish --command=phone_battery_status"
interval = 60

[[block]]
block = "custom"
command = "fish --command='tv_status --barmode'"
interval = 60

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %H:%M"
