[icons]
name = "awesome5"
[icons.overrides]
net_up = ""
net_down = ""
net_wired = ""
toggle_on = ""
toggle_off = ""

[theme]
name = "slick"
[theme.overrides]
separator = ""
separator_bg = "auto"

[[block]]
block = "pacman"
format = "{pacman:0}/{aur:0}"
format_singular = "{pacman:1}/{aur:1}"
format_up_to_date = "{pacman:0}/{aur:0}"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru --query --upgrades --aur 2>/dev/null"
# AUR only allows 4000 requests every 24 hours
interval = 1800
hide_when_uptodate = true
on_click = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-juaninch/ | wofi --show dmenu"

[[block]]
block = "music"
buttons = ["play", "prev", "next"]
marquee = false
max_width = 25

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 60
warning = 5.0
alert = 2.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;G} ({mem_used_percents:1})"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
format = "{utilization1} {utilization2} {utilization3} {utilization4}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "custom"
command = "fish --command='check_vpn --barmode'"
interval = 60

[[block]]
block = "net"
format = " {speed_down;M} {speed_up;M}"
icons_format = "{icon}"

# if have issues then disable this block until it has been cleared of unwraps
# once https://github.com/greshake/i3status-rust/pull/533 is merged this should be easier to monitor
[[block]]
block = "sound"
driver = "pulseaudio"
step_width = 3
max_vol = 99
on_click = "fish --command='switchaudio --menu'"
#on_click = "swaymsg exec 'pavucontrol'"
#this crashes swaybar:
#on_click = "pavucontrol 2>/dev/null"
show_volume_when_muted = true
format = "{output_name} {volume}"
icons_format = " "
[block.mappings]
# pulseaudio
"alsa_output.pci-0000_00_1b.0.analog-stereo" = ""
"alsa_output.usb-Harman_Multimedia_JBL_Pebbles_1.0.0-00.analog-stereo" = "U"
"alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_Play__3_00145592-00.analog-stereo" = "D"
"bluez_sink.20_74_CF_26_25_D0.a2dp_sink" = "BT"
"alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2" = "TV"
"alsa_output.pci-0000_01_00.1.hdmi-stereo-extra3" = "TV"
"alsa_output.pci-0000_01_00.1.hdmi-stereo-extra4" = "TV"
"alsa_output.pci-0000_01_00.1.hdmi-stereo-extra5" = "TV"
# pipewire-pulse
"alsa_output.pci-0000:00:1b.0.analog-stereo" = ""

[[block]]
block = "custom"
command = "fish --command='check_kernel --barmode'"

[[block]]
block = "custom"
# Show number of X11 apps running
command = "fish --command='check_xclients --barmode'"
on_click = "fish --command='check_xclients --menu'"
interval = 5
hide_when_empty = true

[[block]]
block = "kdeconnect"
device_id = "689ccf9fd6f3272d"

[[block]]
block = "weather"
format = "{apparent*_}℃ {humidity}%"
service = { name = "openweathermap", units = "metric" }

[[block]]
block = "toggle"
command_on = "systemctl --user start swayidle"
command_off = "systemctl --user stop swayidle"
command_state = "systemctl --user status swayidle &>/dev/null; test $status -eq 0; and echo on"
icons_format = " {icon}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %H:%M"

[[block]]
block = "toggle"
command_on = "fish --command='sway_setup_tv_gaming'"
command_off = "fish --command='sway_end_tv_gaming'"
command_state = "lgtv audio getVolume"
icons_format = "TV: {icon}"
interval = 60

[[block]]
block = "bluetooth"
mac = "D0:BC:C1:E6:57:5C"
controller_id = "hci1"
format = "OK"
format_disconnected = "D/C"
format_unavailable = "N/A"
[block.theme_overrides]
alternating_tint_bg = "#00000000"
alternating_tint_fg = "#00000000"

[[block]]
block = "battery"
driver = "upower"
device = "gaming_input_ps_controller_battery_d0obcoc1oe6o57o5c"
format = "PS5: {percentage}"
full_format = "PS5: {percentage}"
missing_format = "PS5: N/A"
allow_missing = true
hide_missing = true
on_click = "fish --command='sway_setup_tv_gaming'"

[[block]]
block = "custom"
command = "fish --command='systemd_failed_units'"
hide_when_empty = true
interval = 30

# [[block]]
# block = "battery"
# device = "ps-controller-battery-d0:bc:c1:e6:57:5c"
# allow_missing = true
# hide_missing = true
# [block.theme_overrides]
# alternating_tint_bg = "#00000000"
# alternating_tint_fg = "#00000000"
