icons_format = "{icon}"

[icons]
icons = "awesome6"

[theme]
theme = "slick"
[theme.overrides]
separator = ""
separator_bg = "auto"

[[block]]
# since have title bars disabled on laptop
block = "focused_window"
if_command = '[[ "$(</etc/hostname)" == *"lap"* ]]'
[block.format]
full = " $title |"
short = " $title.str(0,30) |"

[[block]]
block = "pacman"
format = " $icon $pacman.eng(1)/$aur.eng(1) "
format_singular = " $icon $pacman.eng(1)/$aur.eng(1) "
format_up_to_date = ""
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru --query --upgrades --aur 2>/dev/null"
# AUR only allows 4000 requests every 24 hours
interval = 1800
[[block.click]]
button = "left"
cmd = "{ fakeroot pacman -Qu --dbpath /tmp/checkup-db-$USER/ & paru --query --upgrades --aur; } | cat | wofi --show dmenu"
[[block.click]]
button = "right"
cmd = 'foot --app-id scratchpad_dropdown'

[[block]]
block = "music"
if_command = '[[ "$(</etc/hostname)" == *"desk"* ]]'
format = " $icon $combo.rot-str(20) $prev $play $next|"
interface_name_exclude = [".*kdeconnect.*"]
[[block.click]]
button = "middle"
cmd = "allow_only_one_instance sonixd --enable-features=UseOzonePlatform --ozone-platform=wayland"

[[block]]
block = "disk_space"
path = "/"
alert_unit = "GB"
interval = 60
warning = 10.0
alert = 5.0
info_type = "free"
format = " $icon $percentage.eng(2) "

[[block]]
block = "memory"
format = " $icon $mem_free.eng(3,B,G) ($mem_total_used_percents.eng(2)) "
format_alt = "$icon $swap_used_percents.eng(2) "

[[block]]
block = "cpu"
format = " $icon $utilization{ $boost|} "

[[block]]
block = "temperature"
chip = "coretemp-isa-000"
format_alt = " $icon "

[[block]]
block = "load"
interval = 5

[[block]]
block = "custom"
command = "wg show interfaces"
hide_when_empty = true
interval = 5

[[block]]
block = "net"
device = "^mull.*"
format = "$device"
missing_format = ""

[[block]]
block = "net"
format = " ^icon_net_down $speed_down.eng(3,B,M) ^icon_net_up $speed_up.eng(3,B,M) "
[block.icons_overrides]
net_up = ""
net_down = ""
net_wired = ""

[[block]]
block = "sound"
driver = "pulseaudio"
step_width = 3
max_vol = 99
show_volume_when_muted = true
format = " $output_name $volume.eng(2) "
[block.mappings]
# pulseaudio
"alsa_output.pci-0000_00_1b.0.analog-stereo" = ""
"alsa_output.pci-0000_00_1f.3.analog-stereo" = ""
"alsa_output.pci-0000_00_1f.3.analog-stereo.3" = ""
"alsa_output.usb-Harman_Multimedia_JBL_Pebbles_1.0.0-00.analog-stereo" = "U"
"alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_Play__3_00145592-00.analog-stereo" = "D"
"bluez_sink.20_74_CF_26_25_D0.a2dp_sink" = "BT"
"alsa_output.pci-0000_01_00.1.hdmi-stereo-extra2" = "TV"
"alsa_output.pci-0000_01_00.1.hdmi-stereo-extra3" = "TV"
"alsa_output.pci-0000_01_00.1.hdmi-stereo-extra4" = "TV"
"alsa_output.pci-0000_01_00.1.hdmi-stereo-extra5" = "TV"
# pipewire-pulse
"alsa_output.pci-0000:00:1b.0.analog-stereo" = ""
"alsa_output.pci-0000:00:1f.0.analog-stereo.3" = ""
[[block.click]]
button = "left"
cmd = "allow_only_one_instance switchaudio"
[[block.click]]
button = "middle"
cmd = "allow_only_one_instance pavucontrol"

[[block]]
block = "sound"
driver = "pulseaudio"
device = "@DEFAULT_SOURCE@"
device_kind = "source"
max_vol = 99
[[block.click]]
button = "middle"
cmd = "allow_only_one_instance pavucontrol"
[block.theme_overrides]
# switch idle and warning around in order to get warning when mic is *not* muted
idle_fg = { link = "warning_fg" }
idle_bg = { link = "warning_bg" }
warning_fg = { link = "idle_fg" }
warning_bg = { link = "idle_bg" }
# this doesnt work atm. See https://github.com/greshake/i3status-rust/issues/1539
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"

[[block]]
block = "custom"
command = "check_kernel --barmode"
hide_when_empty = true

# Show number of X11 apps running
[[block]]
block = "custom"
command = "check_xclients --barmode"
interval = 5
hide_when_empty = true
[[block.click]]
button = "left"
cmd = "check_xclients --menu"

[[block]]
block = "kdeconnect"
device_id = "689ccf9fd6f3272d"
format = " $icon $bat_charge| $bat_icon| "

[[block]]
block = "weather"
format = " $icon $apparent $humidity "
service = { name = "openweathermap", units = "metric" }

[[block]]
block = "toggle"
command_on = "systemctl --user start swayidle"
command_off = "systemctl --user stop swayidle"
command_state = "systemctl --user status swayidle &>/dev/null; test $status -eq 0; and echo on"
# shouldnt this be default? possible bug from PR1618
format = " $icon "
interval = 10
[block.icons_overrides]
toggle_on = ""
toggle_off = ""

[[block]]
block = "battery"
if_command = '[[ "$(</etc/hostname)" == *"lap"* ]]'
driver = "sysfs"
device = "CMB1"
format = " $icon $percentage{ $time|} |N/A"

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon %a %d %b %H:%M "
#short = "%H:%M"

[[block]]
block = "menu"
if_command = '[[ "$(</etc/hostname)" == *"desk"* ]]'
text = " TV "
[[block.items]]
display = "Start gaming mode"
cmd = "sway_setup_tv_gaming"
[[block.items]]
display = "End gaming mode"
cmd = "sway_end_tv_gaming"
[[block.items]]
display = "Turn off TV"
cmd = "lgtv system turnOff"
[[block.items]]
display = "Set volume to 20"
cmd = "lgtv audio setVolume 20"

[[block]]
block = "bluetooth"
if_command = '[[ "$(</etc/hostname)" == *"desk"* ]]'
mac = "D0:BC:C1:E6:57:5C"
format = " $icon $available{PS5} "
disconnected_format = " $available{D/C} | N/A "
[block.theme_overrides]
# this doesnt work atm. See https://github.com/greshake/i3status-rust/issues/1539
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"

[[block]]
block = "battery"
if_command = '[[ "$(</etc/hostname)" == *"desk"* ]]'
#driver = "upower"
#device = "battery_ps_controller_battery_d0obcoc1oe6o57o5c"
# upower missing devices not supported yet in async ver
driver = "sysfs"
device = "ps-controller-battery-d0:bc:c1:e6:57:5c"
format = " $icon $percentage |N/A"
full_format = "$percentage"
missing_format = ""
[block.theme_overrides]
# this doesnt work atm. See https://github.com/greshake/i3status-rust/issues/1539
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"
[[block.click]]
button = "left"
# TODO: change to confirm menu in case accidentally click on it
cmd = "allow_only_one_instance sway_setup_tv_gaming"

[[block]]
block = "custom"
command = "systemd_failed_units"
hide_when_empty = true
interval = 30
