[icons]
name = "awesome5"
[icons.overrides]
volume_empty = " "
volume_half = " "
volume_full = " "

[theme]
name = "slick"
[theme.overrides]
separator = ""

[[block]]
block = "pacman"
format = "{pacman}/{aur}"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru --query --sysupgrade --aur 2>/dev/null"
# AUR only allows 4000 requests every 24 hours
interval = 1800

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 60
warning = 5.0
alert = 2.0

[[block]]
block = "memory"
display_type = "memory"

[[block]]
block = "cpu"
format = "{utilization}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "custom"
command = "fish --command='check_vpn --barmode'"
interval = 60

[[block]]
block = "net"
device = "wlan0"

# if have issues then disable this block until it has been cleared of unwraps
# once https://github.com/greshake/i3status-rust/pull/533 is merged this should be easier to monitor
[[block]]
block = "sound"
driver = "pulseaudio"
step_width = 3
on_click = "swaymsg exec 'pavucontrol'"
#this crashes swaybar:
#on_click = "pavucontrol 2>/dev/null"
format = "{output_name} {volume}%"
[block.mappings]
"alsa_output.usb-Harman_Multimedia_JBL_Pebbles_1.0.0-00.analog-stereo" = ""
"alsa_output.pci-0000_00_1b.0.analog-stereo" = ""

[[block]]
block = "custom"
command = "fish --command='check_kernel --barmode'"

[[block]]
block = "custom"
# Show number of X11 apps running
command = "fish --command='check_xclients --barmode'"
interval = 5

[[block]]
block = "focused_window"

[[block]]
block = "ibus"
[block.mappings]
"mozc-jp" = "JP"
"xkb:us::eng" = "EN"

[[block]]
block = "battery"
driver = "sysfs"
device = "CMB1"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %H:%M"
